# Generated by Django 4.2.5 on 2023-09-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
